### PR TITLE
Void return

### PR DESCRIPTION
**Pull request by MathiasReker**
Add void return type to functions with missing or empty return statements, but priority is given to @return annotations.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please stop sending these PRs, across all of github.com. They are not helpful. I've filed an abuse request with GitHub. I already asked you nicely to stop when you spammed Guzzle.

**Comment by MathiasReker** [comment]
Hello. I'm sorry my PRs are not helpfull to you. Others appreciate this type of PR. It's not my intention to bother you, so I will stop this kind of PR's on your repo. I did not see the connection between guzzle and this repo.

**Comment by theofidry** [comment]
@MathiasReker I think if only 10% of such PRs are getting merged then it's probably a sign that people do _not_ appreciate this kind of PR.

Looking at your PRs, most of the time it could be a single PR with two commits: an update of PHP-CS-Fixer rules and a second one where you run PHP-CS-Fixer.

Having to wake up to 30 notifications on your repositories all for tiny changes which don't bring much value can be really annoying.

**Comment by GrahamCampbell** [comment]
That is exactly my point. If you would like to contribute, sending a single PR for a maintainer to think on and start a discussion is the way to go. Never send a large burst of PRs to a single org, especially not just for changing code style. This applies to every repo on GitHub, not just those that I (co)-maintain. I don't know how to say this any more clearly.

**Comment by GrahamCampbell** [comment]
> Others appreciate this type of PR.

I don't agree, I'm afraid. A small number of the PRs may have been merged "to make them go away". That is all.

**Comment by MathiasReker** [comment]
Point taken

**Pull request closed without merging**
