### PR TITLE
Added the Valiator method isBoolean

### PR DESCRIPTION
**Pull request by sephedo**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Our variables are always strings though sent they?

**Comment by sephedo** [comment]
Yes all values are in the format of strings this method ensures they are in the format accepted as booleans - Yes, No, 1, 0, On and Off

**Comment by danhunsaker** [comment]
Has some weird indentation, but otherwise it looks sound.

**Comment by jpuck** [comment]
whoops, looks like the tests are not compatible with ye olde php 5.3
I'll update that to use the formal `array()` instead of `[]`

**Comment by jamesj2** [comment]
It's been a year. Any possibility of this getting merged?

**Comment by vlucas** [comment]
This looks pretty solid to me. Has tests and will not affect anyone if they are not using the boolean validator.

**Pull request merged**
