### PR TITLE
if Loader is not immutable, override Apache env vars

### PR DESCRIPTION
**Pull request by GabeMedrash**
This PR fixes https://github.com/vlucas/phpdotenv/issues/39.

I have not written additional tests due to the added complexity of introducing Apache as a dependency of the test suite, but I would be happy to provide some if you would like.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Please follow PSR-2.

**Comment by GabeMedrash** [comment]
Thanks for the review--I ran `phpcs --standard=PSR2 src` and moved the body of the nested `if` within curly braces. The lint now runs clean. Let me know if there's something else you had in mind.

**Comment by GrahamCampbell** [comment]
Nearly there. Please get rid of the nested if too. ;)

**Comment by GabeMedrash** [comment]
Gotcha--think I got it this time!

**Comment by GrahamCampbell** [comment]
Thanks. Looks good to me. Ping @vlucas for approval.

**Comment by vlucas** [comment]
Looks good to me. The only question I have is that we can probably only check if one of the apache get/set functions exist, because if the module is enabled, both of them will always exist. It's more of a minor thing though, and not a reason to hold up this PR.

**Comment by GabeMedrash** [comment]
@vlucas Thanks, that makes a lot of sense. Will modify now.

**Comment by vlucas** [comment]
Thanks 👍

**Pull request merged**
