### PR TITLE
Allow configuration flags to be set within individual .env files

### PR DESCRIPTION
**Pull request by adam-prickett**

### CODE REVIEW

**Comment by stedaniels** [comment]
@vlucas is anything needed to get this merged?  Or do you just not want to do this kind of thing and you're being polite by not saying? :-)  Being too busy too look at it is totally a valid reason.  (I've got three kids under three!)

**Comment by cronfy** [comment]
I do not like the idea that .env file dictates to webserver where to store environment variables. It is also not flexible to put these settings in the .env file.

Why not just have a `load()` equivalent, that only returns array of env variables without touching `$_ENV/$_SERVER/putenv()`, e. g. `read()`? (also see #163).

**Comment by tuupola** [comment]
I am against merging this patch. One should be able to do `$ source .env` and expect the shell to have same environment variables as PHP has after calling `$dotenv->load();`.

**Comment by vlucas** [comment]
I don't like controlling phpdotenv itself with environment variables that it loads. This seems like something that should be in the PHP code or config instead.

**Comment by schmunk42** [comment]
@vlucas I just came across the same issue, like https://github.com/vlucas/phpdotenv/issues/196; several frameworks also log $_SERVER which is populated with ENV variables.

Sure, $_SERVER contains critical values by default, but it should be up to the developer if he wants to *populate* $_SERVER or not.

The current hacky way is to sanitize $_SERVER manually.

**Comment by cronfy** [comment]
I like the way it is solved here: https://github.com/josegonzalez/php-dotenv

```
$Loader = (new josegonzalez\Dotenv\Loader('path/to/.env'))
              ->parse();
```

Then array of options can either be returned via `toArray()` or populate env via `toEnv()`, but it is the developer who decides, where env variables go.

**Comment by GrahamCampbell** [comment]
Replaced by https://github.com/vlucas/phpdotenv/pull/300. See https://github.com/vlucas/phpdotenv#loader-customization for an example.

**Pull request closed without merging**
