### PR TITLE
Cast for variable $string

### PR DESCRIPTION
**Pull request by selcukcukur**
Avoiding random selection.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The type of that variable is already necessarily `string`?

**Comment by selcukcukur** [comment]
@GrahamCampbell Yes, no other value is returned.

**Comment by GrahamCampbell** [comment]
So this PR is unnecessary?

**Comment by selcukcukur** [comment]
May be required in multiple uses. @GrahamCampbell

**Pull request closed without merging**
