### PR TITLE
Removed old branch alias

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Are you able to merge this 1.1->2.0->master?

**Comment by GrahamCampbell** [comment]
Or shall i send a pull to 2.0 too?

**Comment by GrahamCampbell** [comment]
Ping @vlucas. :)

**Comment by GrahamCampbell** [comment]
We need branch alises removing and the master re-aliased as 2.1 before laravel can upgrade to this.

**Comment by GrahamCampbell** [comment]
And the old branches deleted as the "v2" branch can mess with packagist.

**Comment by GrahamCampbell** [comment]
PING - THIS IS URGENT - YOU HAVE BROKEN ALL 1.X CODE BY ALIASING THE MASTER TO 1.1

**Comment by vlucas** [comment]
Sorry - will fix

**Comment by GrahamCampbell** [comment]
Thank you. :)

**Pull request merged**
