### PR TITLE
Tipping dotenv class attirbutes

### PR DESCRIPTION
**Pull request by MarceloOProgramador**
In this modification I tipping the Dotenv.php attributes

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
We can't do this because we need to support order PHP versions. :)

**Comment by MarceloOProgramador** [comment]
But in the dotenv composer.json requirer "php": "^7.1.3 || ^8.0" and from php 7.0 is already accepted typing.

**Comment by GrahamCampbell** [comment]
No, property types are only available from PHP 7.4 onwards.

**Comment by MarceloOProgramador** [comment]
It's true! Sorry bro! ^^'

**Pull request closed without merging**
