### PR TITLE
Added clarity to usage with Composer

### PR DESCRIPTION
**Pull request by tommarmstrong**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 Not normally correct. Just confusing.

**Comment by fabswt** [comment]
Shouldn't the README state:

    php composer.phar require--dev vlucas/phpdotenv

Instead of 

    php composer.phar require vlucas/phpdotenv

?

**Comment by GrahamCampbell** [comment]
Not dev.

**Comment by fabswt** [comment]
And why not then?

The README says:

> phpdotenv is made for development environments, and generally should not be used in production

I'm using Heroku's config vars for production, why would I need to install phpdotenv as `require` instead of `require-dev`?

**Comment by GrahamCampbell** [comment]
> phpdotenv is made for development environments, and generally should not be used in production

That readme line is outdated, and needs fixing. You should not be executing phpdotenv, or indeed, any other similar library using php-fpm, or related. Instead, you should do something like what Laravel's config system does, and cache environment variables into computed config files, using a console command.

**Pull request closed without merging**
