### PR TITLE
Added Validator for allowedRegexvalues

### PR DESCRIPTION
**Pull request by treestonemedia**
- Added a function to check if an env variable's value matches a given regex.
- This was required for our project and I think is a nice addition to this amazing tool.
- Also added a test for allowedRegexValues().
- Also added a readme block.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for the PR. I wonder if we should require exactly one match, rather than at least 1? In your usage, which behaviour would be most useful?

**Comment by treestonemedia** [comment]
@GrahamCampbell good point - that was an oversight on my part - updated the PR

**Comment by GrahamCampbell** [comment]
Perfect. I've made some tweaks, and merged this into master (https://github.com/vlucas/phpdotenv/commit/1bdf24f065975594f6a117f0f1f6cabf1333b156). This will be included in the v3.6.0 release.

**Comment by GrahamCampbell** [comment]
This will be included in the v3.6.0 release. Thanks for the contribution! 🎉

**Pull request closed without merging**
