### PR TITLE
Add some style fixing

### PR DESCRIPTION
**Pull request by lucasmichot**
Add some style fixing

### CODE REVIEW

**Comment by lucasmichot** [comment]
The build fails but for an unrelated reason : https://travis-ci.org/vlucas/phpdotenv/jobs/91935396

**Comment by GrahamCampbell** [comment]
StyleCI's not even enabled here.

**Comment by GrahamCampbell** [comment]
This is quite unnecessary I think.

**Comment by GrahamCampbell** [comment]
StyleCI can be enabled here without any changes.

**Comment by lucasmichot** [comment]
@GrahamCampbell , this PR is not only related to StyleCi ;-)

**Comment by GrahamCampbell** [comment]
I know. StyleCI removes the need for people to bother messing with local config or fixing.

**Pull request closed without merging**
