### PR TITLE
Rewrite parser and fix escaped quotes in multiline values

### LINKED ISSUE #319: Equals Symbol Causes "Failed to parse dotenv file due to an invalid name".
How do you escape the = symbol? It's causing the "Failed to parse dotenv file due to an invalid name" error because of it. It's part of a multiline value.

    SERVICE_ACCOUNT_JSON = '{
        "type": "service_account",
        "project_id": "project id",
        "private_key": "-----BEGIN PRIVATE KEY-----\nMIIE ..... DgQw==\n-----END PRIVATE KEY-----\n",
        "client_email": "email@account.com"
        "client_id": "1234567890123456789",
        .....
        .....
    }',

It is failing at the 2 == symbols at the end of the "private_key" value. If I remove the 2 symbols, it works, but unfortunately, it won't authenticate.

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Closes #319.

### CODE REVIEW

**Comment by drzraf** [comment]
This commit added `symfony/polyfill-ctype` to `composer.json` instead `php[ctype]`.
I can't see the rational of this choice. (And I'd rather before off this extra-dependency)

**Comment by GrahamCampbell** [comment]
This adds the dependency because we are using the ctype functions.

**Comment by GrahamCampbell** [comment]
The `symfony/polyfill-ctype` package has `ext-ctype` as a recommended package. When you install phpdotenv and you don't have the php extension, composer will actually warn you about this, and recommend you install it.

**Comment by drzraf** [comment]
... but if one has `php[ctype]` it installs an unneeded dependency.

**Comment by GrahamCampbell** [comment]
You can stop this happening in your app with the following trick. In your app's composer.json, do this:

```json
{
    ...
    "replace": {
        "symfony/polyfill-ctype": "*"
    },
    "require": {
        ...
        "ext-ctype": "*",
        ...
        "vlucas/phpdotenv": "^3.3"
    },
    ...
}
```

**Pull request merged**
